### ISSUE TITLE
reserve_book

### ISSUE THREAD

**Issue by andreearoj** [SirMatix/mechachrome-mob-app#27]
When I try to reserve a book the app stops running.

**Comment by andreearoj** [comment]
Could you please have a look at it?
Thank you

**Comment by andreearoj** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mechachromemobileapp, PID: 18325
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mechachromemobileapp/com.example.mechachromemobileapp.Activities.Library.ReserveBook}: java.lang.NullPointerException: Provided document path must not be null.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Provided document path must not be null.
        at com.google.firebase.firestore.util.Preconditions.checkNotNull(com.google.firebase:firebase-firestore@@21.4.1:147)
        at com.google.firebase.firestore.CollectionReference.document(com.google.firebase:firebase-firestore@@21.4.1:103)
        at com.example.mechachromemobileapp.Activities.Library.ReserveBook.getBookData(ReserveBook.java:93)
        at com.example.mechachromemobileapp.Activities.Library.ReserveBook.onCreate(ReserveBook.java:58)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by SirMatix** [comment]
fixed it, there was an error with getting extra data from intent
